#ifndef CONFIG_H
#define CONFIG_H

#define GAME_TITLE "Inf vs Zombies"

#define BUTTONS_X 504
#define BUTTONS_Y_OFFSET 24
#define BUTTONS_WIDTH 312
#define BUTTONS_HEIGHT 73
#define BUTTONS_X_GLOW 480
#define BUTTONS_WIDTH_GLOW 360
#define BUTTONS_HEIGHT_GLOW 121
#define MAX_INPUT_NAME 13

#define MAX_HORDES 10
#define TIME_BETWEEN_HORDES 5.0f

#define TILE_TYPE_BUTTON 0
#define TILE_TYPE_GRASS 1

#define GOLDEN_ZOMBIE_CHANCE 5

#define MAX_PLAYERS_LEADERBOARD 5

#define LEADERBOARD_FILE "top_scores.bin"

#define BASE_WIDTH_FLOAT 1280.0f
#define BASE_HEIGHT_FLOAT 720.0f
#define BASE_WIDTH_INT 1280
#define BASE_HEIGHT_INT 720
#define X_OFFSET 96
#define Y_OFFSET 78

#define FRAME_CHANGE_RATE 0.2f

extern const int SELL_POS_X;
extern const int SELL_POS_Y;
extern const int FONT_SIZE;

#define ROWS 7
#define COLUMNS 9
#define GRID_MARGIN_X 418
#define GRID_MARGIN_Y 174

#define MAX_ZOMBIES_ON_SCREEN 50
#define ZOMBIE_HP 100
#define HORDE_SPAWN_TIMER 12.0f
#define ZOMBIE_SPEED 20.0f
#define ZOMBIE_DAMAGE 15
#define ZOMBIE_KILL_SCORE 100
#define ZOMBIE_DMG_CD_SECONDS 1.0f
#define REC_ZOMBIE_WIDTH 40
#define REC_ZOMBIE_HEIGHT 80
#define ZOMBIE_RENDER_WIDTH 72.0f
#define ZOMBIE_RENDER_HEIGHT 90.0f
#define ZOMBIE_SPRITE_FRAME_WIDTH 340.0f
#define ZOMBIE_SPRITE_FRAME_HEIGHT 550.0f

#define SUNFLOWER_ID 16
#define SUNFLOWER_FRAME_ID 0
#define SUNFLOWER_COST 50
#define SUNFLOWER_CD 7.5f
#define SUNFLOWER_LOOPS_GENERATE 20
#define CHIMPAZINI_INITIAL_HP 20
#define CHIMPAZINI_TEXTURE "sunflower"
#define CHIMPAZINI_MONEY_AWARD 50

#define PEASHOOTER_ID 17
#define PEASHOOTER_FRAME_ID 1
#define PEASHOOTER_COST 100
#define PEASHOOTER_CD 7.5f
#define PEASHOOTER_INITIAL_HP 50
#define PEASHOOTER_TEXTURE "peashooter"
#define PEASHOOTER_PROJECTILE_CD 3
#define PROJECTILE_SPEED 400.0f
#define PROJECTILE_DAMAGE 20

#define CHOMPER_ID 18
#define CHOMPER_FRAME_ID 2
#define CHOMPER_COST 150
#define CHOMPER_CD 7.5f
#define CHOMPER_INITIAL_HP 50
#define CHOMPER_TEXTURE "chomper"
#define CHOMPER_LOOPS 30

#define WALLNUT_ID 19
#define WALLNUT_FRAME_ID 3
#define WALLNUT_COST 50
#define WALLNUT_CD 30
#define WALLNUT_TEXTURE "wallnut"
#define WALLNUT_INITIAL_HP 300

#define TACTICAL_CUKE_ID 20
#define TACTICAL_CUKE_FRAME_ID 4
#define TACTICAL_CUKE_COST 25
#define TACTICAL_CUKE_CD 30
#define TACTICAL_CUKE_TEXTURE "tactical_cuke"
#define TACTICAL_CUKE_REIMBURSEMENT 10
#define TACTICAL_CUKE_INITIAL_HP 10
#define TACTICAL_CUKE_LOOPS 15	
#define BOMB_SPEED 1800.0f

#define TARGET_FPS 60
#define BASE_FONT_SIZE 40
#define MONEY_BAG_RANDOMNESS 500
#define MONEY_BAG_AMOUNT 50
#define MAX_PROJECTILES_ON_SCREEN 100
#define REC_PROJ_WIDHT 20
#define REC_PROJ_HEIGHT 20

#define INITIAL_MONEY 150
#define DEFAULT_REIMBURSEMENT_RATE 0.5f

#define SOUND_PROJECTILE 1
#define SOUND_EXPLOSION 17
#define SOUND_CHOMPER 18
#define SOUND_SELECT 2
#define SOUND_COLLECT 3
#define SOUND_COLLECTBAG 4
#define SOUND_CANCEL 5
#define SOUND_PUT 6
#define SOUND_HIT 7
#define SOUND_EAT 8
#define SOUND_END_GAME 9
#define SOUND_BGMUSIC 98

// ReadHordesConfig lê o arquivo de configPath e retorna o array com a configuração de hordas e o número de hordas.
int ReadHordesConfig(char *configPath, int hordes[], int maxHordes);
#endif
